--- 
title: "PLSC 31101: Introduction To Computational Tools And Techniques For Social Research"
author: "Rochelle Terman"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# (PART) Before Class {-}

# Syllabus

* Instructor: [Rochelle Terman](http://rochelleterman.com/), rterman@uchicago.edu

* TA: Pete Cuppernull, pcuppernull@uchicago.edu

* Time: Tuesdays and Thursdays, 12:30 pm – 1:50 pm

* Place: Cobb Hall 303

* Office hours:
	* Rochelle Terman: TBA
	* Pete Cuppernull: TBA


## Course Description

The purpose of this course is to provide graduate students with the critical computing skills necessary to conduct research in quantitative / computational social science. This course is not an introduction to statistics, computer science, or specialized social science methods. Rather, the focus will be on practical skills necessary to be successful in further methods work. The first portion of the class introduces students to basic computer literacy, terminologies, and programming languages, covering Bash, R, and Git. The second part of the course provides students the opportunity to use the skills they learned in part 1 towards practical applications such as webscraping, data collection through APIs, automated text analysis, etc. We will assume no prior experience with programming or computer science.

#### Objectives {-}

By the end of the course, students should be able to:

* Understand basic programming terminologies, structures, and conventions.
* Navigate and operate effectively in a UNIX environment.
* Master basic Git and GitHub workflows.
* Write, execute, and debug R code.
* Produce reproducible analyses using `R Markdown`.
* Clean, transform, and wrangle data using the `tidyverse` packages.
* Scrape data from websites and APIs.
* Parse and analyze text documents.
* Be familiar with the concepts and tools of a variety of computational social science applications
* Be familiar with the basic guidelines around reproducible research, good scientific computing practices, and ethics/privacy/legal quandaries. 
* Learn independently and train themselves in a variety of computational applications and tasks through online documentation.

## Who should take this course

This course is designed for Political Science Graduate students, but any graduate student is welcome. We will not presume any prior programming or computer science experience.

## Requirements and Evaluation

#### Final Grades {-}

This is a graded class based on the following:

* Completion of assigned homework (50%)
* Participation (25%)
* Final project (25%)

#### Assignments {-}

Assignments will be assigned at the end of every session. They will be due at the start of the following class unless otherwise noted. The assignments are intended to expand upon the lecture material and to help students develop the actual skills that will be useful for applied work. The assignments will be frequent but each of them should be fairly short.

You are encouraged to work in groups, but the work you turn in must be your own. Group submission of homework, or turning in copies of the same code or output, is not acceptable. While you are encouraged to use the internet to help you debug, but do not copy and paste large chunks of code that you do not understand. Remember, the only way you actually learn how to write code is to write code!

Portions of the homework completed in `R` should be completed using [R markdown](https://rmarkdown.rstudio.com/), a markup language for producing well-formatted HTML documents with embedded R code and outputs. R markdown requires installation of the `knitr` package. We recommend using [Rstudio](https://www.rstudio.com/), a user interface for R, which is set up well for the creation of R markdown documents.

#### Class Participation {-}

The class participation portion of the grade can be satisfied in one or more of the following ways:

- attending the lectures
- asking and answering questions in class
- attending office hours
- contributing to class discussion through the bCourse site, and/or
- collaborating with the computing community, either by attending a workshop or meetup, submitting a pull request to a campus github repository (including the class repository), answering a question on StackExchange, or other involvement in the social computing / digital humanities community. 

#### Final Project {-}

The final project consists of using the tools we learned in class on your own data of interest. Students are required to write a short proposal by November 7 (no more than 2 paragraphs) in order to get approval / feedback from the instructors. 

On December 5 we will have a **lightning talk session** where students can present their projects in a maximum 5 minute talk.

#### Late Policy and Incompletes {-}
All deadlines are strict. Late assignments will be dropped a full letter grade for each 24 hours past the deadline. Exceptions will be made for students with a documented emergency or illness.

I will only consider granting incompletes to students under extreme personal/family duress.

#### Academic Integrity {-}
I follow a zero-tolerance policy on all forms of academic dishonesty. All students are responsible for familiarizing themselves with, and following, university policies regarding proper student conduct. Being found guilty of academic dishonesty is a serious offense and may result in a failing grade for the assignment in question, and possibtire course.


## Activities and Materials

#### Course Structure {-}

Classes will follow a "workshop" style, combining lecture, demonstration, and coding exercises. We envision the class to be as interactive / hands on as possible, with students programming every session. **You must bring a laptop to class.** 

#### Canvas {-}

We will use Canvas for communication (announcements and questions) and turning in assignments. You should ask questions about class material and assignments through the bcourse website so that everyone can benefit from the discussion. We encourage you to respond to each other’s questions as well. Questions of a personal nature can be emailed to us directly.

#### GitHub {-}

All course materials will be posted on Github at https://github.com/rochelleterman/TBD, including class notes, code demonstrations, sample data, and assignments. Students are encouraged to submit pull requests to this repository, for example if they find a particularly helpful resource that would aid other students. Students are required to use GitHub for their final projects, which will be publically available, unless they have special considerations (e.g. proprietary data). 

#### Computer Requirements and Software {-}

By the end of the first week, you should install the following software on your computer:

* Access to the UNIX command line (e.g., a Mac laptop, a Bash wrapper on Windows)
* Git
* R and RStudio (latest versions)

This requires a computer that can handle all this software. Almost any Mac will do the job. Most Windows machines are fine too if they have enough space and memory.

See [Install.md](Install.md) for more information. We will be having an **InstallFest** on TBD for those students experiencing difficulties downloading and installing the requisite software.

#### Readings and Resources (REVISIT) {-}

There are no official textbooks for this class. There is a list of topic-specific tutorials and resources in the GitHub repo in the document `resources.md`. If you find a good online resources, you are encouraged to add to the document. 

## Curriculum Outline / Schedule

1. **Oct 1** - Introduction 
	* course objectives, logistics, overview of programming and reproducible research.

2. **Oct 3** - R Basics 
    * R Studio, basic syntax, packages, getting help, R Markdown.

3. **Oct 8** - R Objects and Data Structures
    * data structures, classes, coercions, attributes, vectors, lists, factors, matrices, data frames.

4. **Oct 10** - Indexing and Subsetting
    * subsetting formats, operators, boolean conditionals, sub-assignment,  applications.

5. **Oct 15** - Introduction to Data
    * common terms, formats, tidy data, storage, import/export, exploratory data analysis.
     
6. **Oct 17** Manipulating data with dplyr
    * importing data, subsetting, summarizing, and conducting calculations across groups, piping.

7. **Oct 22** - Tidying data with tidyr
    * tidy data principles, gather, spread, separate, unite.

8. **Oct 24** - Merging and Linking Data 
    * relational data, keys, joins, missing values.

9. **Oct 29** - Hypothesis testing and regressions
    * models, model objects, stargazer,

10. **Oct 31** - Visualization
    * base plotting, ggplot, grammar of graphics, writing images. 

11. **Nov 5**- R programming 1
    * strings, conditional flow, booleans. 
    
12. **Nov 5** - R Programming 2
    * functions, iterations, apply family.

13. **Nov 12** - Collecting data with APIs
    * requests, RESTful APIs, queries, API libraries.

14. **Nov 14**  - Webscraping
     * HTML, CSS, In-Browser tools, scraping tools.

15. **Nov 19**  - Text analysis 1
    * supervised vs. unsupervised learning, Vector-space models, topic models
   
16. **Nov 21** - Text analysis 2
    * supervised vs. unsupervised learning, Vector-space models, topic models

17. **Nov 26** - Regex

18. **Nov 28** - Git / Github

19. **Dec 3** - Final project lightning talks

20. **Dec 5** - Final project lightning talks
